import { useState, useEffect } from 'react';
import Button from 'react-bootstrap/Button';

const timeFormatter = new Intl.DateTimeFormat("en-US", {"timeStyle": "short"});

function AgeGuesser() {
  const [name, setName] = useState(null);
  const [age, setAge] = useState(null);

  function guessAge(name) {
    fetch(`https://api.agify.io/?name=${name}`)
      .then(response => response.json())
      .then(result => setAge(result.age));
  }

  function handleNameChange(e) {
    setName(e.target.value);
  }

  function handleSubmit(e) {
    guessAge(name);
  }

  return (
    <>
      <input type="text" id="name" onChange={handleNameChange}/>
      <Button variant="primary" size="lg" onClick={handleSubmit} disabled={!Boolean(name)}>
        Guess Your Age
      </Button>
      <span id="age-guess">{age !== null ? `We guess your age to be ${age}` : ""}</span>
    </>
  )
}

function DigitalClock() {
  const [time, setTime] = useState(timeFormatter.format(new Date()));

  useEffect(
    () => {
      let interval = setInterval(() => setTime(timeFormatter.format(new Date())), 60000);
      return () => clearInterval(interval);
    },
    []
  );

  return <div id="digital-clock" style={{"fontFamily": "monospaced", "color": "green"}}>{time}</div>
}

function JokeContainer() {
  const [joke, setJoke] = useState("loading a joke...");

  function updateJoke() {
    fetch("https://v2.jokeapi.dev/joke/Any?blacklistFlags=nsfw,religious,political,racist,sexist,explicit&type=single")
     .then(response => response.json())
     .then(response_json => setJoke(response_json.joke))
  }

  useEffect(
    () => {
      let interval = setInterval(updateJoke, 60000);
      return () => clearInterval(interval);
    },
    []
  );

  return <div id="joke-container">{joke}</div>
}


function RandomDogPicture() {
  const [url, setUrl] = useState(null);

  useEffect(
    () => {
      fetch("https://random.dog/woof.json")
        .then(response => response.json())
        .then(data => setUrl(data.url))

      return () => setUrl(null);
    },
    []
  );

  if (url) {
    return (
      <>
        <span>Here's a random dog picture from dog.random</span>
        <img id="dog-picture" width="400" height="400" src={url} alt={"A random picture of a dog"}/>
      </>
    );
  } else {
    return <span>Loading dog picture</span>;
  }
}


export default function JavascriptExamples() {
  return (
    <>
      <div id="clocks">
        <canvas id="analog-clock" width="150" height="150" style={{"backgroundColor": "#999"}}></canvas>
        <DigitalClock/>
      </div>
      <div id="external-content">
        <aside>Please note: The content contained here and the clock animation above were generated by external sites and are not my work.</aside>
        <JokeContainer/>
        <AgeGuesser/>
        <RandomDogPicture/>
      </div>
    </>
  )
}
